import { getRandomInt } from '../../../utils/rand'

export function genNomEmpire(male) {
  var nom = PRENOMS_F[getRandomInt(PRENOMS_F.length)]
  if (male) nom = PRENOMS_M[getRandomInt(PRENOMS_M.length)]
  nom = nom + ' ' + NOMS[getRandomInt(NOMS.length)]
  return nom
}

const PRENOMS_F = ['Abbie']
const PRENOMS_M = ['Abelhard']
const NOMS = [
  'Adelhof',
  'Albrecht',
  'Allenstag',
  'Altmann',
  'Atzwig',
  'Bacher',
  'Baer',
  'Baumann',
  'Becker',
  'Behn',
  'Betz',
  'Beyer',
  'Bischof',
  'Boehm',
  'Breitenbach',
  'Breuer',
  'Dahmbach',
  'Delfholt',
  'Drakenhof',
  'Drauwulf',
  'Durrbein',
  'Ehrhard',
  'Eisenhauer',
  'Eschlimann',
  'Falkenheim',
  'Fehr',
  'Fiegler',
  'Fleischer',
  'Frohlich',
  'Frueh',
  'Fuchs',
  'Gaffwig',
  'Gaertner',
  'Gebauer',
  'Godtgraf',
  'Grunenwald',
  'Guth',
  'Haintz',
  'Herz',
  'Herzog',
  'Hirtzel',
  'Hoch',
  'Hoefer',
  'Hofstetter',
  'Jaeger',
  'Jochutz',
  'Jutzenbach',
  'Kalb',
  'Kaltenbach',
  'Kraemer',
  'Krebs',
  'Kuhn',
  'Kummel',
  'Konig',
  'Konigsamen',
  'Lang',
  'Lankdorf',
  'Liess',
  'Lebengut',
  'Lutzen',
  'Machholt',
  'Meusmann',
  'Meyer',
  'Mohr',
  'Muller',
  'Nachtmann',
  'Naubhof',
  'Netzhoch',
  'Neumann',
  'Niederlitz',
  'Nuhr',
  'Oberholtzer',
  'Ohrsten',
  'Otzlowe',
  'Reichert',
  'Reifsneider',
  'Riese',
  'Rohrig',
  'Reiss',
  'Schaffer',
  'Schaumer',
  'Scherer',
  'Schultz',
  'Schleirmacher',
  'Schreiber',
  'Schwalb',
  'Steiner',
  'Tabbeck',
  'Teuber',
  'Tolzen',
  'Trachsel',
  'Weber',
  'Wechsler',
  'Wirtz',
  'Widmann',
  'Zumwald',
  'Widmer',
  'Veit',
  'Vogt',
  'Vogel',
]
